version: '3.7'
services:
  protonvpn-manager:
    container_name: protonvpn-manager
    #image: qmcgaw/gluetun:v3
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
    ports:
      - "8080:8080"

  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    network_mode: "service:protonvpn-manager"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - protonvpn-manager
      #protonvpn-manager:
      #  condition: service_healthy
    volumes:
      - ./tailscale/state:/var/lib/tailscale
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=proton-torpedo-node1
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_USERSPACE=true
    restart: unless-stopped
    env_file:
      - .env

